-- AlterTable
ALTER TABLE "Insurance" ADD COLUMN     "accumulatedBonus" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "accumulatedSumIncrease" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "insurer" TEXT,
ADD COLUMN     "isPeriodicPayout" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "lastUpdatedAt" TIMESTAMP(3),
ADD COLUMN     "policyNumber" TEXT,
ADD COLUMN     "sumInsured" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "surrenderValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ALTER COLUMN "declaredRate" SET DEFAULT 0,
ALTER COLUMN "premiumTotal" DROP NOT NULL,
ALTER COLUMN "currentAge" SET DEFAULT 0,
ALTER COLUMN "cashValueData" SET DEFAULT '[]';
